config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :add_on_malls , :only => [:index, :new, :create, :edit, :update, :destroy] do
    end
  end


  namespace :admin , :only => [] do
      resources :products , :only => [] do
        get 'add_on_mall_prices' => 'add_on_mall_prices#index'
        resources :variants do
          get 'add_on_mall_prices/edit',      to: 'add_on_mall_prices#edit'
          patch 'add_on_mall_prices', to: 'add_on_mall_prices#update'
          resources :add_on_mall_prices, :only => [:new, :create] do
        end
      end
    end
  end

end

app/models/spree/ability_decorator.rb
class AbilityDecorator
  include CanCan::Ability
  def initialize(user)
    #can [:read, :index], Spree::NewsEntry

    if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
      can [:admin, :index, :read, :update, :edit], Spree::AddOnMall
      can [:admin, :index, :read, :update, :edit], Spree::AddOnMallPrice
    end
  end
end

Spree::Ability.register_ability(AbilityDecorator)

app/models/spree/add_on_mall.rb
module Spree
  class AddOnMall < ActiveRecord::Base
    has_many :add_on_mall_prices
    acts_as_paranoid

    validates :name, presence: true
    validates_uniqueness_of :name
    accepts_nested_attributes_for :add_on_mall_prices
  end
end

app/models/spree/add_on_mall_price.rb
module Spree
  class AddOnMallPrice < ActiveRecord::Base
    belongs_to :variant, class_name: 'Spree::Variant', :foreign_key => :variant_id
    belongs_to :add_on_mall, class_name: 'Spree::AddOnMall', :foreign_key => :add_on_mall_id
    validates_uniqueness_of :add_on_mall_id, :scope => :variant_id
    validates_uniqueness_of :amount, :scope => [:add_on_mall_id, :variant_id], allow_nil: true
    validates_uniqueness_of :currency, :scope => [:add_on_mall_id, :variant_id], allow_nil: true
  end
end

app/models/spree/add_on_mall_translation.rb
module Spree
  AddOnMall.class_eval do
    translates :name, :presentation, :fallbacks_for_empty_translations => true
    include SpreeI18n::Translatable
  end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    has_many :add_on_mall_prices, class_name: 'Spree::AddOnMallPrice'

#   enable variants to CRUD each own add_on_maker_variants by accept nesting as child
    accepts_nested_attributes_for :add_on_mall_prices, allow_destroy: true

  end
end

app/controllers/spree/admin/add_on_mall_prices_controller.rb
module Spree
  module Admin
    class AddOnMallPricesController < ResourceController
      before_filter :load_data

      def new
        session[:return_to] ||= request.referer
        @add_on_malls = Spree::AddOnMall.includes(:add_on_mall_prices).all
        @add_on_mall_prices = Spree::AddOnMallPrice.where(:variant_id => params[:variant_id])
      end

      def show
        session[:return_to] ||= request.referer
        redirect_to( :action => :edit )
      end

      def index
        session[:return_to] = request.url
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        if @product.has_variants?
          @variant = @product.variants.page(params[:page])
        else
          @variant = Spree::Variant.where(:id => @product.master.id).page(params[:page])
        end
        render :index
      end

      def edit
        session[:return_to] = request.url
        @add_on_malls = Spree::AddOnMall.order(:name)
#        @add_on_malls = Spree::AddOnMall.includes(:add_on_mall_prices).where(Spree::AddOnMallPrice.arel_table[:variant_id].eq(params[:variant_id])).references(:add_on_mall_prices).order(:name)
        @add_on_mall_prices = Spree::AddOnMallPrice.includes(:add_on_mall).where(:variant_id => params[:variant_id])
        render :edit
      end

      def create
        begin
          params[:add_on_mall_prices].each_value { |value|
            @add_on_mall_prices = Spree::AddOnMallPrice.new(value)
            @add_on_mall_prices.save
            }
              respond_to do |format|
              flash[:success] = t('add_on.notice_messages.admin_product_variant_add_on_mall_price_variant_created')
                format.html { redirect_to admin_product_add_on_mall_prices_path }
              format.json { render action: 'index', status: :created, location: @add_on_mall_prices }
              end
        rescue
              respond_to do |format|
              flash[:error] = t('add_on.notice_messages.admin_product_variant_add_on_mall_price_variant_has_error')
              format.html { render action: 'new' }
              format.json { render json: @add_on_mall_prices.errors }
              end
        end

      end

      def update
        begin
          params[:add_on_mall_prices].each_value { |value|
            @add_on_mall_prices = Spree::AddOnMallPrice.where(:variant_id => value["variant_id"], :add_on_mall_id => value["add_on_mall_id"]).first_or_initialize
            @add_on_mall_prices.update(value)
            logger.info @add_on_mall_prices.errors.inspect
            }
          respond_to do |format|
            flash[:success] = t('add_on.notice_messages.admin_product_variant_add_on_mall_price_variant_updated')
            format.html { redirect_to :action => :index }
            format.json { head :no_content }
          end
        rescue
          respond_to do |format|
            flash[:error] = t('add_on.notice_messages.admin_product_variant_add_on_mall_price_variant_has_error')
            format.html { render action: 'edit' }
            format.json { render json: @add_on_mall_price_variant.errors }
          end
        end
      end

      def destroy
        @variant = Spree::Variant.find(params[:id])
        if @variant.destroy
          flash[:success] = Spree.t('notice_messages.variant_deleted')
        else
          flash[:success] = Spree.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_maker_variant_path(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

  protected
      def variant_includes
        [:add_on_mall_price_variants]
      end

      def load_data
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @taxons = Taxon.order(:name)
        @option_types = OptionType.order(:name)
        @tax_categories = TaxCategory.order(:name)
        @shipping_categories = ShippingCategory.order(:name)
        @add_on_malls = Spree::AddOnMall.order(:name)
      end

  private
      def permit_attributes
        params.require(:add_on_mall_prices).value.permit!
      end

      def add_on_mall_price_variant_params
        params.require(:add_on_mall_prices).value.permit(:variant_id, :add_on_mall_id, :amount, :currency)
      end

    end
  end
end

app/controllers/spree/admin/add_on_malls_controller.rb
module Spree
  module Admin
    class AddOnMallsController < ResourceController

      def update_values_positions
        params[:positions].each do |id, index|
          AddOnMall.where(:id => id).update_all(:position => index)
        end

        respond_to do |format|
          format.html { redirect_to admin_add_on_malls_url(params[:id]) }
          format.js  { render :text => 'Ok' }
        end
      end

      def index
        @add_on_mall = Spree::AddOnMall.page(params[:page])
      end

  private
      def add_on_mall_params
        params.require(:add_on_mall).permit(add_on_mall_prices_attributes: [ :variant_id, :add_on_mall_id, :amount, :currency ])
      end
    end
  end
end

app/controllers/spree/admin/variant_controller_decorator.rb
Spree::Admin::VariantsController.class_eval do
  before_filter :load_add_on_mall_price, :only => :load_data

  def load_add_on_mall_price
    @add_on_mall_price = Spree::AddOnMallPrice.where(:variant_id => @variant.id).first
    logger.info "####### loaded_add_on_mall_price ########"
    logger.info @add_on_mall_price
  end

  private
      def variant_params
        params.require(:variant).permit(add_on_mall_price_attributes: [ :variant_id, :mall_id, :amount, :currency])
      end
end

app/views/spree/admin/add_on_mall_prices/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Mall Price Variants'} %>

<% content_for :page_title do %>
  <%= t('add_on.add_on_mall_price') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('add_on.back_to_product_add_on_mall_prices_list'), admin_product_add_on_mall_prices_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<% if @add_on_malls.empty? %>
  <%= t('add_on.mall_is_not_registered_yet') %><br>
  <%= link_to t('add_on.please_create_add_on_malls'), new_admin_add_on_mall_path %>
<% else %>
  <%= form_tag(admin_product_variant_add_on_mall_prices_path(:variant_id => params[:variant_id]), {method: 'patch', action: 'update'}) do %>
  <table class='index'>
    <thead>
      <tr>
        <th><%= t("activerecord.attributes.add_on_mall.name") %></th>
        <th><%= t("activerecord.attributes.add_on_mall_price.amount") %></th>
        <th><%= t("activerecord.attributes.add_on_mall_price.currency") %></th>
      </tr>
    </thead>
    <tbody>
      <% @add_on_malls.each_with_index do |add_on_mall,index| %>
      <tr class="<%= cycle('odd', 'even') %>">
      <td class="align-center">
      <%= hidden_field_tag "[add_on_mall_prices][#{index}][variant_id]", params[:variant_id] %>
      <%= hidden_field_tag "[add_on_mall_prices][#{index}][add_on_mall_id]", add_on_mall.id %>
      <%= add_on_mall.name %>
      </td>
      <td>
        <% unless add_on_mall.add_on_mall_prices.blank? %>
          <%= text_field_tag "[add_on_mall_prices][#{index}][amount]", add_on_mall.add_on_mall_prices.first.amount, :autofocus => true %>
        <% else %>
          <%= text_field_tag "[add_on_mall_prices][#{index}][amount]",nil ,:autofocus => true %>
        <%end%>
      </td>
      <td>
        <% unless add_on_mall.add_on_mall_prices.blank? %>
          <%= text_field_tag "[add_on_mall_prices][#{index}][currency]", add_on_mall.add_on_mall_prices.first.currency%>
        <% else %>
          <%= text_field_tag "[add_on_mall_prices][#{index}][currency]", Spree::Config[:currency] %>
        <%end%>
      </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= submit_tag Spree.t(:update) %>
  <% end %>

<% end %>

app/views/spree/admin/add_on_mall_prices/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Mall Price Variants'} %>

<% content_for :page_title do %>
  <%= t("add_on.listing_add_on_mall_prices") %>
<% end %>

<% if @add_on_malls.empty? %>
  <%= t('add_on.mall_is_not_registered_yet') %><br>
  <%= link_to t('add_on.please_create_add_on_malls'), new_admin_add_on_mall_path %>
<% else %>

  <%= paginate @variant %>

  <table class='index'>
    <thead>
      <tr>
        <th><%= t("activerecord.attributes.variant.id") %></th>
        <th><%= Spree.t(:options) %></th>
        <th><%= Spree.t(:price) %></th>
        <th><%= Spree.t(:sku) %></th>
      </tr>
    </thead>

    <tbody>
      <% for variant in @variant %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td class="align-center"><%= variant.id %></td>
          <td class="align-center"><%= variant.options_text %></td>
          <td class="align-center"><%= variant.price %></td>
          <td class="align-center"><%= variant.sku %></td>

          <% if variant.add_on_mall_prices.empty? %>
          <td class="actions"><%= link_to t("edit"), ("/admin/products/" + params[:product_id] + "/variants/#{variant.id}/add_on_mall_prices/new") , :class => 'edit' %></td>
          <% else %>
          <td class="actions"><%= link_to t("edit"), ("/admin/products/" + params[:product_id] + "/variants/#{variant.id}/add_on_mall_prices/edit") , :class => 'edit' %></td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/add_on_mall_prices/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Mall Price Variants'} %>

<% content_for :page_title do %>
  <%= t('add_on.add_on_mall_price') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('add_on.back_to_product_add_on_mall_prices_list'), admin_product_add_on_mall_prices_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<% if @add_on_malls.empty? %>
  <%= t('add_on.mall_is_not_registered_yet') %><br>
  <%= link_to t('add_on.please_create_add_on_malls'), new_admin_add_on_mall_path %>
<% else %>

  <%= form_tag(admin_product_variant_add_on_mall_prices_path(:variant_id => params[:variant_id]), {method: 'post'}) do %>
  <table class='index'>
    <thead>
      <tr>
        <th><%= t("activerecord.attributes.add_on_mall.name") %></th>
        <th><%= t("activerecord.attributes.add_on_mall_price.amount") %></th>
        <th><%= t("activerecord.attributes.add_on_mall_price.currency") %></th>
      </tr>
    </thead>
    <tbody>
      <% @add_on_malls.each_with_index do |add_on_mall,index| %>
      <% @add_on_mall_prices = add_on_mall.add_on_mall_prices.build(:currency => Spree::Config[:currency], :variant_id => params[:variant_id]) %>
      <tr class="<%= cycle('odd', 'even') %>">
      <td class="align-center">
      <%= hidden_field_tag "[add_on_mall_prices]#{index}[variant_id]", params[:variant_id] %>
      <%= hidden_field_tag "[add_on_mall_prices]#{index}[add_on_mall_id]", add_on_mall.id %>
      <%= add_on_mall.name %>
      </td>
      <td>
          <%= text_field_tag "[add_on_mall_prices]#{index}[amount]",@add_on_mall_prices.amount, :autofocus => true %>
      </td>
      <td>
          <%= text_field_tag "[add_on_mall_prices]#{index}[currency]",@add_on_mall_prices.currency %>
      </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= submit_tag "Save" %>
  <% end %>

<% end %>

app/views/spree/admin/add_on_malls/_form.html.erb
<%= form_for [:admin, @add_on_mall] do |f| %>
  <div data-hook="admin_inside_bank_form" class="row">
    <div class="alpha five columns">
      <%= f.field_container :name do %>
        <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
        <%= f.error_message_on :name, :class => 'fullwidth title' %>
        <%= f.text_field :name, :class => 'fullwidth' %>
      <% end %>

      <%= f.submit %>

    </div>
  </div>
<% end %>

app/views/spree/admin/add_on_malls/edit.html.erb
<% content_for :page_title do %>
  <%= t("add_on.edit_mall") %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t("add_on.back_to_malls_list"), admin_add_on_malls_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'form' %>

app/views/spree/admin/add_on_malls/index.html.erb
<% content_for :page_title do %>
  <%= t("add_on.listing_add_on_mall") %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t("add_on.new_add_on_mall"), new_admin_add_on_mall_path , :icon => 'icon-plus', :id => 'admin_new_add_on_mall'%>
  </li>
<% end %>

<%= paginate @add_on_mall %>

<table class='index'>
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.add_on_mall.name") %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @add_on_mall.each do |mall| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= mall.name %></td>
        <td class="actions"><%= link_to_edit mall, :no_text => true, :class => 'edit' %></td>
        <td class="actions"><%= link_to_delete mall, :no_text => true if can?(:delete, mall) && !mall.deleted? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/add_on_malls/new.html.erb
<% content_for :page_title do %>
  <%= t("add_on.new_add_on_mall") %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t("add_on.back_to_add_on_malls_list"), admin_add_on_malls_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'form' %>    